# for reference see https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD046/code-block-style - Code block style
MD046: false

# MD013/line-length - Line length
MD013: false
